### ISSUE TITLE
Assignment 1

### ISSUE THREAD

**Issue by shankarkharel** [Des-Vu-Technologies/Fly_with_flutter#1]
![Assignment1 drawio](https://github.com/Des-Vu-Technologies/Fly_with_flutter/assets/59717384/f53d4c79-489a-4e8b-a056-2afe9dd54c4f)
Make a UI Similar to the image and post your ss to  this issue

**Comment by shushal19** [comment]
This is the screenshot of my output
<img width="349" alt="Screenshot 2023-10-19 at 21 14 35" src="https://github.com/Des-Vu-Technologies/Fly_with_flutter/assets/59756277/747eb3ac-9921-47ba-b479-5596f435eace">

**Comment by SafalTimsina** [comment]
This is my Output.

https://github.com/Des-Vu-Technologies/Fly_with_flutter/assets/136340870/36853391-5e20-40b4-a811-0d5f8f81fca9

**Comment by NabinTimsina-17** [comment]
This is my first assignment work
![Screenshot 2023-10-25 162423](https://github.com/Des-Vu-Technologies/Fly_with_flutter/assets/133372145/03969673-247d-45f7-bc73-6e1b97bf2b0b)
