### ISSUE TITLE
Assignment-2

### ISSUE THREAD

**Issue by shankarkharel** [Des-Vu-Technologies/Fly_with_flutter#3]
Make the UI similar to this :
![Assignment-2](https://github.com/Des-Vu-Technologies/Fly_with_flutter/assets/59717384/e3d95e45-c7da-4be3-a409-d501ad36c547)

**Comment by kashyapsandesh** [comment]
<img width="1679" alt="Screenshot 2023-10-27 at 17 30 42" src="https://gi
<img width="1680" alt="Screenshot 2023-10-27 at 17 30 22" src="https://github.com/Des-Vu-Technologies/Fly_with_flutter/assets/88843968/be5af9d9-d77c-47e9-8a61-
<img width="1674" alt="Screenshot 2023-10-27 at 17 30 32" src="https://github.com/Des-Vu-Technologies/Fly_with_flutter/assets/88843968/a3ff93cb-9d67-4475-939d-acc6f2b8fc0c">
5f559b40a4e1">
thub.com/Des-Vu-Technologies/Fly_with_flutter/assets/88843968/8b3fe576-b76d-4264-963b-e7562261abd6">

**Comment by kashyapsandesh** [comment]
<img width="1656" alt="Screenshot 2023-10-27 at 17 34 47" src="https://github.com/Des-Vu-Technologies/Fly_with_flutter/assets/88843968/45acce35-c4e7-4f90-8aaa-b5affbe00314">

**Comment by kashyapsandesh** [comment]
<img width="1680" alt="Screenshot 2023-10-27 at 17 30 22" src="https://github.com/Des-Vu-Technologies/Fly_with_flutter/assets/88843968/9c80fd41-7b57-496c-b2fa-264627418d0c">
