### ISSUE TITLE
ASSIGNMENT-3 UI 

### ISSUE THREAD

**Issue by shankarkharel** [Des-Vu-Technologies/Fly_with_flutter#4]
UI Designing:
Make UI similar to:
![1_fm6XPKNS9l9ZAyWZqsqyVA](https://github.com/Des-Vu-Technologies/Fly_with_flutter/assets/59717384/919a4ef2-db88-4fcc-8d17-d60aee3388dd)

**Comment by Katwal07** [comment]
![login_signup_page](https://github.com/Des-Vu-Technologies/Fly_with_flutter/assets/151430847/fb27a4d9-a865-4e96-9681-c114f423e5f8)

**Comment by shankarkharel** [comment]
Good Work!
